modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial 3.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
    modId="overtime"
    version="${file.jarVersion}"
    displayName="SCP Overtime"
    # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    displayURL="https://discord.gg/sxDyCTng"
    logoFile="logo.png"
    credits="Tac0dile and Sir.Pancakes for help with models and Concept Build. ConnorTron110 for code."
    authors="Gusutab0"
    description='''
    A tribute to the SCP Foundation gaming community such as SCP Containment Breach and SCP Unity and many others.
    '''

[[dependencies.overtime]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.overtime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
