name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
assignees:
  - ConnorTron110
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: Overtime Version
      description: What version of Overtime are you running?
      options:
        - v0.0.1.0 (Latest)
    validations:
      required: true
  - type: input
    attributes:
      label: Forge Version
      description: What version of Forge are you using?
      placeholder: e.g. v36.1.32
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (generated JSONs, code snippets) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: markdown